version: "3.7"

services:
  nn:
    image: hungict2407/custom-namenode:1.0.0
    ports:
      - 9870:9870
    volumes:
      - nn-data:/home/storage/hdfs/namenode

    networks:
            - recommender

  dn001:
    image: hungict2407/custom-datanode:1.0.0
    volumes:
      - dn001-data:/home/storage/hdfs/datanode
    ports:
      - 9865:9864

    networks:
            - recommender

  dn002:
    image: hungict2407/custom-datanode:1.0.0
    volumes:
      - dn002-data:/home/storage/hdfs/datanode
    ports:
      - 9866:9864

    networks:
            - recommender

  mn:
    image: hungict2407/custom-spark:1.0.0
    command: sh -c "sbin/start-master.sh -h mn -p 7000 && sbin/start-worker.sh -p 7001 spark://mn:7000 && tail -f README.md"
    ports:
      - 8080:8080
    networks:
            - recommender

  w001:
    image: hungict2407/custom-spark:1.0.0
    command: sh -c "sbin/start-worker.sh -p 7001 spark://mn:7000 && tail -f README.md"
    networks:
            - recommender
    depends_on:
      - mn

  ms:
    image: model-server:1.0.4
    ports:
      - 5000:5000
        #    volumes:
        #      - .:/code
    networks:
            - recommender
  sql:
    image: mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: hungvs
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: movies
    ports:
      - "3307:3306"
    networks:
      - recommender

  server:
    # build: ./server
    image: hungict2407/web-server:1.0.0
    restart: always
    ports:
      - "5001:5001"
    networks:
      - recommender
    depends_on:
      - sql

  client:
    # build: ./client
    image: hungict2407/web-client:1.0.0
    ports:
      - "3000:3000"
    networks:
      - recommender
    depends_on:
      - server

networks:
    recommender:
            #          external: true

volumes:
  nn-data:
  dn001-data:
  dn002-data:
  mysql-data:
