version: '3'

services:
  database:
    image: mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: root123
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: movies
    ports:
      - "3307:3306"
    networks:
      - network_1
      
  server:
    image: hungdz3112/server
    restart: always
    ports:
      - "5000:5000"
    networks:
      - network_1
    depends_on:
      - database

  client:
    image: hungdz3112/client
    ports:
      - "3000:3000"
    networks:
      - network_1
    depends_on:
      - server

volumes:
  mysql-data:

networks:
  network_1:
    name: custom_network