version: "3.7"

services:
  app:
    image: server
    build: .
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root12345678
      MYSQL_USER: root
      MYSQL_PASSWORD: root12345678
      MYSQL_DATABASE: test
    ports:
      - 3306:3306

volumes:
  todo-mysql-data:

networks:
  default:
    external:
      name: todo-app