version: '3'

services:
  client:
    image: client
    build: ../client/.
    ports:
      - "3000:3000"
    depends_on:
      - server
      
  server:
    image: server
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: root123
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: movies
    ports:
      - "3307:3306"

volumes:
  mysql-data:
